### ISSUE TITLE
Still the same issue with granted -v 0.1.8  - assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

### ISSUE THREAD

**Issue by daknhh** [common-fate/granted#103]
https://aws.amazon.com/blogs/developer/assume-aws-iam-roles-with-mfa-using-the-aws-sdk-for-go/

**Comment by daknhh** [comment]
still not working in granted -v 0.1.11

Error:
`assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.`

**Comment by JoshuaWilkes** [comment]
Hi @daknhh 

In the latest release, we have tested using MFA in a few different configurations as described in the description of #123 
Let us know if this issue still persists for you

**Comment by daknhh** [comment]
Hi @JoshuaWilkes  now its working fine <3 thank you so much - great work - great tool
