### ISSUE TITLE
got a "fork/exec : no such file or directory" message since 0.1.6 release

### ISSUE THREAD

**Issue by waltzbucks** [common-fate/granted#104]
I've using the linux desktop environment to Ubuntu 20.04.

I use this config profiles on it.

```
[profile temp-cred]
region = ap-northeast-2
output = json
credential_process = python /home/username/.aws/get-temp-credentials.py --device arn:aws:iam::000000000000:mfa/mydevice --otpkey (MFA_SECRET_KEY) --profile default

[profile myassume]
region=ap-northeast-2
source_profile = temp-cred
role_arn = arn:aws:iam::1111111111111:role/myassume
output = json
```

`get-temp-credentials.py` script from this [repo](https://github.com/waltzbucks/aws-get-temporary-credentials/tree/main)

Then me, `assume -c myassume` it works until 0.1.6 release.  But I've run into this message when upgraded to from 0.1.6 release to 0.1.8 releases.

```bash
$ assume -c myassume                                                                                                                                                        1 ↵
fork/exec : no such file or directory
```

**Comment by meyerjrr** [comment]
Hey @waltzbucks
Are you still able to use that credential process when running `assume myassume` (without opening the console) to assume the role?
More than likely something has broken in the browser code rather than the credential process as that was not changed in the latest release.
Also could you send through what is in your `~/.granted/config` file, should help with the debug process if it is related to the browsers change.

**Comment by waltzbucks** [comment]
Hi @meyerjrr 

I've still using `granted` version is 0.1.5. it's works it web browser open to federation endpoint with that was got a temporary credential as assume by credential_process output of python script. But, a future version not work it with this error message `fork/exec : no such file or directory`

`~/.granted/config` file is :

```
DefaultBrowser = "FIREFOX"
CustomBrowserPath = "/usr/bin/firefox"
LastCheckForUpdates = 0
```

Browser info:
```
Name = Firefox
Version = 98.0
Build ID = 20220304153049
```

Browser extension: Granted Containers
```
Version = 1.0.3
Last Updated = February 24, 2022
```

Thanks for taking care of it.

**Comment by meyerjrr** [comment]
Hey @waltzbucks, could you try install granted v0.1.9 and see if the issue persists?

We fixed an issue opening browsers with a custom path which may have been related to this issue.

**Comment by waltzbucks** [comment]
Hi @meyerjrr,  I've tried to with v0.1.9 release then it's work! So amazing.

Thank you so much
