### ISSUE TITLE
assume not working with chained roles

### ISSUE THREAD

**Issue by jbl-proglove** [common-fate/granted#108]
Hi,

first of all, thanks for this great tool, since I jump around between dozens of AWS accounts each day this is really a great addition!

When trying to use a combination of an assume-role chained with an AWS SSO auth, I get an error:

My `~/.aws/config` contains this:
```ini
[profile jump-account]
sso_start_url = https://REDACTED.awsapps.com/start/#
sso_region = eu-west-1
sso_account_id = FIRST-ACCOUNT-ID
sso_role_name = some-role
region = eu-west-1
output = json

[profile target-account]
source_profile = jump-account
role_arn =  arn:aws:iam::OTHER-ACCOUNT-ID:role/TargetRole
output = json
region = eu-west-1
```

When I first do an `aws sso login --profile jump-account` and then run a command like `aws s3 ls --profile target-account`, everything works.

When I try to do this using `assume`, I get:
```bash
bsh ❯  assume jump-account

[jump-account](eu-west-1) session credentials will expire 2022-03-15 20:29:39 +0100 CET

bsh ❯ assume target-account
operation error STS: AssumeRole, https response error StatusCode: 400, RequestID: 2aa7685d-04ac-406a-a2a7-ee4f48b196db, api error ValidationError: 1 validation error detected: Value '' at 'tokenCode' failed to satisfy constraint: Member must have length greater than or equal to 6
```

Some things to add:
* the role in the target account (`arn:aws:iam::OTHER-ACCOUNT-ID:role/TargetRole`) can be assumed by the role setup for AWS SSO, of course
* AWS SSO is setup in the `jump-account` (`FIRST-ACCOUNT-ID`)

Is this case supposed to work, or just not supported (yet)?

Please let me know if there is anything I can help you with - apparently, this would resolve the one thing left to fully rely on this nice setup!

**Comment by JoshuaWilkes** [comment]
This looks to be an issue with MFA, based on the tokenCode error.

Do you have MFA setup for this target-account role?
Possibly some default MFA configured?


Out of the box, Granted will work with most role chaining with SSO roles however we haven't tested this with chaining to a role that requires MFA

**Comment by jbl-proglove** [comment]
Hi Joshua!

Thanks for the quick reply. MFA is configured for my AWS SSO user right inside AWS SSO. The target account (or the role therein) does not have any MFA requirements / settings.
Please note that we do not use any IAM users - since these are the entities in IAM where you can attach MFA.

Is MFA supported in general?
Is there anything I can provide - logs, configs - to find out more?

**Comment by dannysteenman** [comment]
The same issue happens on my system (MacOS) I have a similar chained role setup as @jbl-proglove

**Comment by jbl-proglove** [comment]
Thanks a lot for the fix, works perfectly now!
