### ISSUE TITLE
Some of your credentials are missing. Please contact your administrator.

### ISSUE THREAD

**Issue by michal-michalak** [common-fate/granted#109]
Hey guys, 

I would like to try your product cause it looks awesome but I spent a few hours struggling with this weird AWS error. Any ideas what's wrong? 

Error:
```
Some of your credentials are missing. Please contact your administrator.
```

AWS config (account number changed):
```
[profile tga]
region = us-west-1
[profile tga-assume]
region = us-west-1
source_profile = tga
role_arn = arn:aws:iam::123321:role/AdministratorRole
```

AWS credentials (keys changed):
```
[tga]
aws_access_key_id = ABC
aws_secret_access_key = DEF
[tga-assume]
aws_access_key_id = ABC
aws_secret_access_key = DEF
```

<img width="1624" alt="aws" src="https://user-images.githubusercontent.com/10532319/158629956-3437acf0-a53c-4981-a21e-e6e25ebf9631.png">

**Comment by meyerjrr** [comment]
Thanks for flagging this @michal-michalak! I have just opened a PR fixing this issue, so should be functional in the next patch.

**Comment by michal-michalak** [comment]
@meyerjrr Just tested that on `Version: 0.1.10`. Works like a charm. Thank you and have a great day! 🙂
