### ISSUE TITLE
zsh autocompletion

### ISSUE THREAD

**Issue by dannysteenman** [common-fate/granted#110]
As mentioned in the [docs](https://docs.commonfate.io/granted/configuration#autocompletion):

_Granted has support for shell auto complete. We currently support fish, with plans to support [bash, powershell, and zsh](https://github.com/urfave/cli/tree/master/autocomplete) in the future. Please let us know of your interest by [opening an issue on GitHub](https://github.com/common-fate/granted/issues)._

I haven't found an open github issue on this request so here's one to let you know that I would be interested in zsh autocompletion for granted!

To be more specific, having the ability to tab and then be able to automatically search you aws config for profiles.

Here's something I use for `aws-vault` to autocomplete aws profiles in zsh: https://github.com/dannysteenman/zsh-aws-vault/blob/main/_aws_vault_completion

**Comment by JoshuaWilkes** [comment]
Thanks @dannysteenman 

In the meantime, running `assume` on its own will give you a searchable list of profiles to assume from your AWS config.

**Comment by dannysteenman** [comment]
Hi, @JoshuaWilkes I figured that out indeed and it is a cool feature however, my muscle memory disagrees with it 😂
