### ISSUE TITLE
Cannot assume IAM profiles on windows

### ISSUE THREAD

**Issue by JoshuaWilkes** [common-fate/granted#116]
On behalf of a slack user.

In Windows powershell, Granted fails to launch the console with either an IAM profile with credentials in the .credentials file or a profile in the .config file which references a source_profile 

e.g 

# config
[profile creds]
region = ap-southeast-2

[profile dev]
region = ap-southeast-2
source_profile = creds

# credentials 
[creds]
aws_access_key_id=
aws_secret_access_key=

**Comment by mkallistos** [comment]
Hi Josh, as mentioned, here is my config the same as requested above. Additionally, I've added role_arn in the profile:

***config***
[default]
region = ap-southeast-2
output = json

[profile creds]
region = ap-southeast-2

[profile dev]
region = ap-southeast-2
role_arn = arn:aws:iam::1234:role/GrantedAdmin
source_profile = creds

***credentials***

[creds]
aws_access_key_id = XXX
aws_secret_access_key = XXX
region=ap-southeast-2
