### ISSUE TITLE
[Feature request] One-liner command execution with `--exec`

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#120]
From the Common Fate Community Slack:

> Does assume take a profile argument and then execute a single command given? This would rock for use in shell scripts. for PROFILE in $(cat profile_list.txt); do assume $PROFILE --exec COMMAND_OR_SHELL_SCRIPT; done would be great. 

We should add a `--exec` flag which allows a command to be passed through to be executed as the profile.

**Comment by meyerjrr** [comment]
fixed in #125
