### ISSUE TITLE
Unable to launch browser in Windows

### ISSUE THREAD

**Issue by eigBabcock** [common-fate/granted#121]
I'm using Granted version 0.1.11 on Windows 10. When I assume a role (not logged into AWS), my browser opens and requests for permissions just fine. However, every time afterwards I have been unable to get a browser window to pop when I assume different roles. The logs indicate that I can switch roles (`[Build-Account](us-west-2) session credentials will expire...`), but nothing happens. I've tried launching through both Chrome and Edge browsers, and have verified that the paths are set correctly in my settings (`granted settings`).

**Comment by JoshuaWilkes** [comment]
Hi @eigBabcock 

To confirm you are running `assume -c <profile-name>`
Do you get a URL in the terminal to open in the browser or does nothing happen at all?
