### ISSUE TITLE
Support SSO authentication in a non-default browser

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#132]
From Marco on the Common Fate Community Slack:

I just discovered this software and I’m experimenting with it. I’m having some issues with the browser flow: my default browser is Chrome, but I’d like to use Firefox for the SSO Authentication flow; even if I’ve configured everything correctly (at least I think I do), when I run assume -c myprofile  the login flow always opens with Chrome.

.granted/config:
```
DefaultBrowser = "FIREFOX"
CustomBrowserPath = "/Applications/Firefox.app/Contents/MacOS/firefox"
```
.aws/config (redacted):
```
[profile myprofile]
sso_start_url=https://foo.bar/
sso_region=eu-west-1
sso_account_id=123456
sso_role_name=myRole
region=eu-west-1
output=json
```

Currently the SSO prompt always opens in the default browser, even if Firefox is used for AWS console access.

For some users (like myself) this is preferred, however other users like Marco would prefer to use Firefox for both SSO authentication and console access.

We should allow users to set an `SSOBrowserPath` in Granted's config file, and open this rather than the default browser if it is set.

```
DefaultBrowser = "FIREFOX"
CustomBrowserPath = "/Applications/Firefox.app/Contents/MacOS/firefox"
SSOBrowserPath = "/Applications/Firefox.app/Contents/MacOS/firefox"
```

**Comment by JoshuaWilkes** [comment]
This was fixed in #169
