### ISSUE TITLE
GetFederationToken 'Member must have length less than or equal to 32'

### ISSUE THREAD

**Issue by TryTryAgain** [common-fate/granted#141]
└❯ assume -c AssumeRole-$ACCOUNT_ID-$ROLE_NAME

> operation error STS: GetFederationToken, https response error StatusCode: 400, RequestID: ..., api error ValidationError: 1 validation error detected: Value 'Granted@AssumeRole-$ACCOUNT_ID-$ROLE_NAME' at 'name' failed to satisfy constraint: Member must have length less than or equal to 32

I see `aws-vault` had solved this by truncating. https://github.com/99designs/aws-vault/pull/377 

...but in my case since we've standardized around a large amount of common data in the front ie: `AssumeRole-$ACCOUNT_ID-...` I wonder if simply truncating would lead to collisions/issues; like if I wanted two or more granted console sessions open how would it handle if the only difference is at the `-$ROLE_NAME` section of that member name?...I'm guessing it wouldn't if it was truncated outright. And had me thinking instead of simply truncating, if possible, it would be better to compare against the existing list of credential "containers" as well as to come up with something unique and identifiable but also deal with truncating to a length of 32 or less.

**Comment by meyerjrr** [comment]
Thanks for the issue @TryTryAgain! and thanks for looking into a solution for the issue too. 
I'm going to go ahead and push through the truncation update so long names can be assumed using GetFederationToken()

If you could give it a try on release and let us know by opening a new issue if you are running into conflicts with names?

For creating unique names... optionally we could hash the name to shorten it, but that leads to a reduction in UX as now the context from the name is lost in the hash.
The main problem is there is no great way to know what console sessions are currently active, so best method to create unique names is to create unique at launch.
We will look into it.

**Comment by TryTryAgain** [comment]
Hello @meyerjrr and @JoshuaWilkes  ... I have upgraded to the latest release v0.1.14 but I'm actually getting the exact same error :(

**Comment by chrnorm** [comment]
@meyerjrr just looking at #145 I wonder if the root cause here is an off-by-one problem with the trucation:
```go
if len(name) > 32 {
		name = name[0:32]
	}
```

may need to be 
```go
if len(name) > 32 {
		name = name[0:31]
	}
```

**Comment by TryTryAgain** [comment]
Good catch, @chrnorm yes ... looks like it 👍

**Comment by JoshuaWilkes** [comment]
@TryTryAgain 

This is odd, using the latest v0.1.14 I am unable to reproduce this error when using the get federation code with a profile name longer than 32 chars.

Could you try uninstalling and reinstalling granted?
`brew remove granted`
`brew install granted`

and retry?

**Comment by TryTryAgain** [comment]
HI @JoshuaWilkes I was pretty sure I had done that before, strange, tried again and I am now receiving a new error:

`operation error STS: GetFederationToken, https response error StatusCode: 403, RequestID: 5d029b3b-9e3a-46dd-b043-1f4e50fb06ec, api error AccessDenied: Cannot call GetFederationToken with session credentials`

so I suppose there was some other thing going on before and now I have a new problem to solve. Thanks for pointing out the obvious, thanks for the quick fix too; hope I don't experience too many conflicts/collisions once I get going here...
