### ISSUE TITLE
Unable to remove tokens from the keychain 

### ISSUE THREAD

**Issue by meyerjrr** [common-fate/granted#149]
Removing tokens from the keychain results in the following error: 
```
Keychain Error. (-25244)
```

To reproduce run either
```
granted token clear
or 
granted token clear --all
```

**Comment by mikeTKOh** [comment]
I got the same thing. I believe this is because /usr/local/bin/granted application is not allowed in the "Access Control" tab of  the Keychain item. After I added the app, I was able to clear.
