### ISSUE TITLE
Question: assume  prompts for password

### ISSUE THREAD

**Issue by engrun** [common-fate/granted#160]
Hi and thanks for a great tool!

But I do have an issue with this, maybe it is a misconfiguration on my side. 

When running assume to open a new session in tab
```
assume -c <profile>
```
I am always prompted for password , like this
```
❯ assume -c <profile>
? Enter passphrase to unlock "/Users/username/.granted/cred-store" 

```
No difference with or without the -c flag. 

I'm also, especially first thing in the morning, being prompted for password twice. 
First time it opens a tab in chrome (my default) 
Then password has to be typed again, and this time opening in firefox (configured for granted)

**It gets kinda annoying to constantly be prompted for password, is there a way around this?**

**Comment by JoshuaWilkes** [comment]
Hi @engrun 

We have had a few people with this issue and it seems to be related to the keyring library that we are using.
See this similar issue #139 
We don't have a fix for this currently.

**Comment by JoshuaWilkes** [comment]
@engrun 

Following up on this, are you using Granted on a mac?
If so, try adding this in your `~/granted/config` file to force granted to use your keychain, which is the expected default, however we have had some issues with it.

```
[Keyring]
  Backend = "keychain"
```

**Comment by engrun** [comment]
> @engrun
> 
> Following up on this, are you using Granted on a mac? If so, try adding this in your `~/granted/config` file to force granted to use your keychain, which is the expected default, however we have had some issues with it.
> 
> ```
> [Keyring]
>   Backend = "keychain"
> ```

On a mac, yes. 
And that actually works 👍
