### ISSUE TITLE
[Feature request] Add flag to write credentials to ~/.aws/credentials under profile name headers.

### ISSUE THREAD

**Issue by timkinnane** [common-fate/granted#164]
My team is using Granted and love it, but also need to augment it with the [SSOcred utility](https://github.com/PredictMobile/aws-sso-credentials-getter) to copy temporary credentials to the user home AWS credentials path.

The `--env` flag is so close to what we need, but some of our tools use legacy connection methods and expect the credentials to be at `~/.aws/credentials ` and we can't update them to read from an `.env` instead.

It would be great to have a flag to export to that path and group credentials under the `[<profile_name>]` header.

**Comment by chrnorm** [comment]
Hey @timkinnane, thanks for the issue! This is something we are keen to support.

Adding some extra context here from a community member in Slack who ran into a similar problem:

> I work with a lot of tools that use the [SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) as a means of loading a name based profile for an application. Is there any support with the granted tool for writing credentials to the ~/.aws/credentials file after assuming an SSO profile. I know that it breaks the security paradigm of the tool but it would be useful as an option to support tools like this.

It might also be worth having a config setting in `~/.granted/config` to allow users to write credentials to `~/.aws/credentials` by default.

**Comment by timkinnane** [comment]
Such a great response on this. Thanks @meyerjrr! 🥇
