### ISSUE TITLE
Granted doesn't work with Serverless Framework

### ISSUE THREAD

**Issue by TimekillerTK** [common-fate/granted#165]
This is an _awesome_ tool! Thank you so much for making it!

[Serverless framework](https://github.com/serverless/serverless) is having trouble using tokens generated by granted for some reason:
> AWS profile "\<profile name\>" doesn't seem to be configured

and

> Credentials not set for profile \<different profile\>

I've used the [shell alias](https://docs.commonfate.io/granted/internals/shell-alias) to export environment variables (and confirmed that they are indeed being exported) with no luck.

We have an internal tool written in bash which fulfills the same role as `granted`, but works with [serverless framework](https://github.com/serverless/serverless). I'm not sure why this is the case as the variables exported by both tools are largely the same, one difference is that our tool requires the user to run `aws sso login` prior to using it to switch roles (which generates a file with sso cache at `/Users/<user>/.aws/sso/cache/<some hash>.json`).

I suspect it may be related to: https://github.com/common-fate/granted/issues/155

**Comment by timkinnane** [comment]
This might be related to #164 as well. We use SLS too and it does require the [shared credentials file](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-file.html). There may be a way to get it to read from the CLI profile session, but that's not been easy, so we just Granted together with [SSOCred](https://github.com/PredictMobile/aws-sso-credentials-getter) to do the job currently.

**Comment by Cosmo439** [comment]
I wrote a small script to generate the shared credentials file from the environment variables.

```
function aws-env() {
    local PROFILE_NAME=${1-$AWS_PROFILE}
    assume $PROFILE_NAME

    echo "Configuring v1 profile: ${PROFILE_NAME}"

    aws --profile $PROFILE_NAME configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    aws --profile $PROFILE_NAME configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    aws --profile $PROFILE_NAME configure set aws_session_token $AWS_SESSION_TOKEN
    aws --profile $PROFILE_NAME configure set aws_session_expiration $AWS_SESSION_EXPIRATION

    echo "Successfully configured profile: ${PROFILE_NAME}"
}
```

This lets me use it with the serverless framework.

**Comment by chrnorm** [comment]
@timkinnane thanks for the issue! And @Cosmo439 thanks for the helpful bash script!

We have added support for this in #168, although it wasn't well documented. I've improved our documentation here and we now have a dedicated page for this use case: https://docs.commonfate.io/granted/usage/export-credentials. 

I'll close this issue for now but if the `--export` flag doesn't work for you with Serverless Framework please reopen it and we'll take a deeper look. Thanks 😁

**Comment by timkinnane** [comment]
Awesome stuff, thanks @Cosmo439 - our teams have already put this to use and I don't think there's been any issues.
