### ISSUE TITLE
Slow with large number of AWS Profiles

### ISSUE THREAD

**Issue by andymac4182** [common-fate/granted#172]
Hi,

I manage a large number of AWS profiles due to managing a few thousand AWS accounts. My `~/.aws/config` file is 7000 lines long. Every call to `assume` takes 10-20 seconds on my macbook pro 16inch M1 Pro laptop. 

Not sure if there is something I can configure to reduce the lookup times.

**Comment by andymac4182** [comment]
Thanks @chrnorm. I love how Granted works this is my main issue.

**Comment by Dvation** [comment]
Same issue here ... ~7500 lines in config and experiencing the same delay when running `assume` commands

**Comment by JoshuaWilkes** [comment]
The resolution here will be to defer loading the full profile configuration until a profile is selected. This will reduce loading times to milliseconds.

**Comment by andymac4182** [comment]
Thanks @JoshuaWilkes 👍
