### ISSUE TITLE
[Feature Request] SSO Browser Profile

### ISSUE THREAD

**Issue by RichiCoder1** [common-fate/granted#183]
For browsers that support profiles (Chrome, Edge, and Chromium Variants), it'd be great to not only launch a specific browser for SSO but to also support launching a specific browser _profile_.

For context, I have a separate Work profile already which is ideally the one launched for SSO sessions.

**Comment by john-fitsense** [comment]
This would be useful for people, such as myself, who use multiple browser profiles (eg work vs personal).
Is there a way to invoke the browser with a specific profile (argument)?

It looks like the pull request was rejected/abandoned!?  I can't find any of the solution in master?  Is this correct?  So the issue remains open.

**Comment by johnmee** [comment]
This would be useful for people, such as myself, who use multiple browser profiles (eg work vs personal).
Is there a way to invoke the browser with a specific profile (argument)?

It looks like the pull request was rejected/abandoned!? I can't find any of the solution in master? Is this correct? So the issue remains open.

**Comment by shwethaumashanker** [comment]
With [v0.16.0](https://github.com/common-fate/granted/releases/tag/v0.16.0), Launching a specific browser profile is now possible with `--browser-profile`. Try `assume profile-name -c --browser-profile "<your_browser_profile>"`

**Comment by johnmee** [comment]
No joy: still opens the default profile:
* Firefox v117.0.1 (64-bit) snap for ubuntu
* Granted Containers v1.1.2 on Firefox installed to both default and alternate profiles

`firefox -p AltProfile` successfully opens firefox with the alternate profile. Their configs are held under `/home/<username>/snap/firefox/common/.cache/mozilla/firefox/<randomstring>.<profilename>`

`assume <awsprofilename> -c --browser-profile AltProfile`  still opens up firefox with the default browser profile.  I tried putting AltProfile in double quotes or using the registered email address for the profile to no avail.

Not sure what I'm doing wrong :-(

**Comment by meyerjrr** [comment]
Hey @johnmee, this fix was specifically for chromium profiles! But we can definitely expand this out for Firefox profiles too.
I've made a new issue that we can use to track progress on: #486
