### ISSUE TITLE
pwsh: assume.ps1 does not work if assumego is not on path

### ISSUE THREAD

**Issue by fdx-wayne-yeap** [common-fate/granted#185]
Preconditions: 
Install granted binaries in a directory that isn't on the PATH

What happens:
The assume.ps1 file does not work if assumego is not on the path.

What should happen
The assume.ps1 file should call the assumego that is in the same directory as the ps1 file instead.

Version:
assume --version: 0.2.0

**Comment by JoshuaWilkes** [comment]
Is is possible to have the ps1 script detect assume on either path or in the current working directory?
I imagine some users will want to run assume from anywhere?

**Comment by fdx-wayne-yeap** [comment]
The Windows install instructions seem to want us to put the .ps1 and .bat scripts in the same directory as the assumego.exe file

But when they call it they assume that assumego is on the path and doesn't check in the current directory (even though it will be if you follow the directions)
