### ISSUE TITLE
[Feature Request] Add support for Google Cloud Compute (GCP)

### ISSUE THREAD

**Issue by pedro93** [common-fate/granted#193]
Hello!

Would like to request support for GCP in assume. This is a wonderful tool for AWS account management, have used it very well in the past. My job now requires that I manage GCP as well as AWS, hence this feature request.

Thanks!

**Comment by ellie-narducci** [comment]
Also raised in #277

**Comment by shwethaumashanker** [comment]
I'm going to close this issue as it appears to be a duplicate. Please refer to: https://github.com/common-fate/granted/issues/277
