### ISSUE TITLE
[Feature Request] Use role_session_name as session identifier if present

### ISSUE THREAD

**Issue by dpolombodkt** [common-fate/granted#199]
Prior to commit https://github.com/common-fate/granted/commit/0b0be89dee39dcda17dcc4040297ae58b3366472, it was possible to declare a role_session_name from .aws/config, but now it is completely ignored. 

The main reason I'd like to use this is to have session identification parity with the web console and identity federation.

Would it be possible to check for that value first, and only generate a unique session identifier if there is no explicit role_session_name?

**Comment by JoshuaWilkes** [comment]
Thanks for the request @dpolombodkt we will get this sorted for you

**Comment by pdecat** [comment]
Submitted https://github.com/common-fate/granted/pull/226 to address this feature request.
