### ISSUE TITLE
The -s flag should imply --console

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#201]
From the Common Fate Community Slack:

> I don’t think using -s by itself does anything, I don’t see why I can’t just do assume -s iam foobar-users-acct or even assume -c iam foobar-users-acct

I think our initial implementation here can be defaulting to opening the console if `assume -s iam <profile>` is used to avoid the need for the `-c` flag to be provided.

**Comment by cmddx** [comment]
Done and done. Fixed in #204 which has now been merged into main.
