### ISSUE TITLE
`assume -c -ar` does not work with `--sso` option

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#213]
To reproduce:

run

```
 assume --sso --sso-start-url https://{DIRECTORY}.awsapps.com/start --sso-region ap-southeast-2 --account-id {ACCOUNT} --role-name GrantedAdministratorAccess
```

you will receive an output similar to the below

```
❯ assume -c -ar
you tried to use the -active-role flag but GrantedAdministratorAccess does not match any profiles in your AWS config or credentials files
```

**Comment by JoshuaWilkes** [comment]
the activeRole flag is currently meant to assume based on the AWS_PROFILE variable. 
Do you want this ticket to add granted_ exports for the sso params so that when running `--ar` it detects that an sso profile was used, and assumes it?

@chrnorm

**Comment by chrnorm** [comment]
@JoshuaWilkes hmmm this might be problematic due to #212, where we need to remove the `AWS_PROFILE` export from `--sso` as it breaks the AWS CLI. My desired effect is that after running `assume --sso --sso-start-url ...` (having pasted this snippet from Granted Approvals) I can easily pop open a console to the role which I've assumed.

I realised that running
```
assume --sso --sso-start-url ... -c
```

actually works but this is a bit annoying as I need to open up my web browser again and copy the snippet a second time.

To clarify - by adding granted_ exports, do you mean adding an env var like `GRANTED_AWS_PROFILE` so that `-c -ar` will work?

**Comment by JoshuaWilkes** [comment]
We could export all the sso params

```
GRANTED_SSO=true
GRANTED_SSO_START_URL=...
GRANTED_SSO_ROLE_NAME=...
```

These are exported when the sso command is used and unset when a normal profile is used.
Then if you use --sso ... you can always put --ar in front of subsequent commands to launch using the sso profile form earlier.

This will work by checking for these env vars, and if they exist, using them in the same way that the AWS_PROFILE is used

**Comment by chrnorm** [comment]
That sounds like a good approach!
