### ISSUE TITLE
Trying to set browser on WSL and path validation is too strict

### ISSUE THREAD

**Issue by lorengordon** [common-fate/granted#215]
I am trying to use granted in Windows Subsystem for Linux (WSL), using Ubuntu 20.04. I have Firefox and Chrome both installed, but granted can't find them and is prompting me for the install path. In WSL, the browsers are still installed to Windows, and the drive is mounted to Linux. So the path is `/c/Program Files/Mozilla Firefox/firefox.exe`. Which `granted` keeps saying is not valid:

```
? Please enter the full path to your browser installation for Firefox: /c/Program\ Files/Mozilla\ Firefox/firefox.exe

❌ The path you entered is not valid
```

But it is:

```
❯ ls /c/Program\ Files/Mozilla\ Firefox/firefox.exe
'/c/Program Files/Mozilla Firefox/firefox.exe'
```

I also tried creating an alias and just specifying `firefox`, but that also resulted in the same error. 

```
? Please enter the full path to your browser installation for Firefox: firefox

❌ The path you entered is not valid
```

But when I run the alias, it works fine!

**Comment by cmddx** [comment]
I looked into this and it seems like Go's file opening systems don't work with the standard WSL format. Paths have to be entered in a format like `/../../mnt/c/Program Files/Mozilla Firefox/firefox.exe` instead. 

I've opened a PR #237 that should make this process a bit easier.

**Comment by lorengordon** [comment]
That's very strange. Is the leading `/` intentional, or a typo? That would imply it is treating the location of the granted/assume binaries as the root of the system, e.g. `/`, and then processing a relative path from there? I wonder why that is? I use terraform and terragrunt pretty extensively, both also written in Go, and they don't seem to process paths any differently for WSL Ubuntu vs "regular" Ubuntu.

**Comment by cmddx** [comment]
You're right - I might actually be able to just start the path with `/mnt/` or `/c/` and have it work.

In terms of the issue with spaces - I've still got no idea. Seems that `os.Stat` in Go fails when there's a `\` that tries to escape the space. Works just fine without the `\` though. I looked into it a bit more and it seems to be an issue on Mac too, we just hadn't encountered it yet because I guess the auto-detection wizard was working on Macs.

**Comment by lorengordon** [comment]
The path on my system is different (`/c/Program Files/Mozilla Firefox/firefox.exe`), so the new "search paths" still fail to find the program, but I can confirm that 0.2.9 does work if I give it the full path with no backslashes or other escaping or quoting.

```
❯ granted browser set

? Select one of the browsers from the list Firefox

ℹ️  Granted could not detect an existing installation of Firefox at known installation paths for your system.
If you have already installed this browser, you can specify the path to the executable manually.

? Please enter the full path to your browser installation for Firefox: /c/Program Files/Mozilla Firefox/firefox.exe

ℹ️  In order to use Granted with Firefox you need to download the Granted Firefox addon: https://addons.mozilla.org/en-GB/firefox/addon/granted.
This addon has minimal permissions and does not access any web page contents (https://granted.dev/firefox-addon).

? Open Firefox to download the extension? Yes

? Type Y to continue once you have installed the extension Yes

✅  Granted will default to using Firefox.
```
