### ISSUE TITLE
env variable AWS_CONFIG_FILE is ignored

### ISSUE THREAD

**Issue by nocode99** [common-fate/granted#229]
I work with a lot of AWS accounts and often I use `AWS_CONFIG_FILE` environment variable to logically separate my config files so I don't have one giant messy one. `aws-vault`, for example, picks this up and reads from there. It helps when giving demo's/presentations not to show the other profiles that I have.

https://github.com/99designs/aws-vault/blob/9a931236194799be720676abf17889ad7d3ec53b/vault/config.go#L39

**Comment by iainelder** [comment]
Any progress on this since #232?

I separate my config files for each environment I work in - org A, org B, org C, and so on.

To work with assume I have to copy one of those config files to the default path `~/.aws/config`.

It would be more convenient and cleaner to respect the AWS_CONFIG_FILE variable.

**Comment by iainelder** [comment]
Glad to see a solution for this. When will you release it?

**Comment by shwethaumashanker** [comment]
Hi @iainelder! We released it yesterday as a part of [v0.15.0](https://github.com/common-fate/granted/releases/tag/v0.15.0). If you already haven't, you can join our [Slack community](https://join.slack.com/t/commonfatecommunity/shared_invite/zt-q4m96ypu-_gYlRWD3k5rIsaSsqP7QMg) for updates on each release or view our newly started [changelog](https://commonfate.notion.site/Granted-Changelog-e44b9a3c649c42ca8faa6a4a1b3121b9) 😄

**Comment by iainelder** [comment]
For now I've subscribed to the releases on GitHub so I can stay up to date. I might join Slack if I have more detailed questions. Thanks for the invitation and the great work on improving the access experience. granted is one of the tools I trust to build a solid access foundation.
