### ISSUE TITLE
Windows command prompt assume script does not export the AWS_PROFILE variable correctly

### ISSUE THREAD

**Issue by JoshuaWilkes** [common-fate/granted#243]
Example, a profile named Security-Admin can be assumed correctly

But when running an AWS command, it fails with

`cannot find profile Securi`

Where the profile name has been cutoff.

This does **not** happen when using the powershell script

**Comment by shwethaumashanker** [comment]
This issue was fixed with https://github.com/common-fate/granted/pull/465!
