### ISSUE TITLE
--exec does not work for programs requiring a TTY [CLI-15]

### ISSUE THREAD

**Issue by sosheskaz** [common-fate/granted#250]
Simple replication: `assume --exec 'vi test.txt'`

Solution doesn't appear to be trivial, but I think it would be good to (at least have an option to) use it with a TTY, so that interactive programs may be run.

**Comment by chrnorm** [comment]
Thanks @sosheskaz. I think the improvements discussed to solve #216 may be a starting point towards fixing this.

If you come across any good open source Go implementations which handle TTY please share them here - it would be good to look at some reference implementations to guide our approach.
