### ISSUE TITLE
Can granted/assume launch browser session using existing temp creds?

### ISSUE THREAD

**Issue by j--wong** [common-fate/granted#273]
Hi,

Just wondering if `granted/assume` can work with existing temporary creds in `~/.aws/credentials` file without assuming a role again?

The scenario is that we are already using temporary credentials and we'd like to use the multiple browser sessions feature of `granted` using existing creds.

Would that be possible?

Thanks,
Josh

**Comment by JoshuaWilkes** [comment]
Hi @j--wong sorry for the long delay in getting back to you.

We have a PR up that is related to your request. #334 

And I have another which I think should solve this issue for you. #335

When merged, `assume` will respect the existing sessionToken when it is present on a profile in ~/aws/credentials
