### ISSUE TITLE
Auto Populated SSO Config should have an option to use the `granted_*` prefix to enable credential process. 

### ISSUE THREAD

**Issue by sherifabdlnaby** [common-fate/granted#313]
## Use case
When using Auto Populate SSO Config, the profiles work perfectly in Terminal, however, a GUI Application (ex: K8S' Lens) won't be apple to authenticate without `credentials_process`, which works when I manually edit the auto-populated SSO Configs. **To make things easier** it will be awesome if populate command had a flag to generate the profiles using `granted_*` prefix.

**Comment by JoshuaWilkes** [comment]
Hey @sherifabdlnaby thanks for the issue!
I'm going to close this as a duplicate of #270 , You can keep track of the implementation/progress there
