### ISSUE TITLE
[FR] Include the a rerun command as part of CLI output when running `assume`

### ISSUE THREAD

**Issue by grantjoy** [common-fate/granted#341]
If someone were to run `assume` or `assume -c`, then select role `Account/MyRole`, it would be nice if the CLI showed `assume -c Account/MyRole` as output.

Users could easily copy that line to rerun if another session were needed. This change would lend to people having easier access (through copy-paste and then command history) to their prior commands.

**Comment by JoshuaWilkes** [comment]
Good idea, we also have `assume --ar` which will read the `AWS_PROFILE` environment variable and assume the same profile again.

Should be simple to add a command output and a hint to use the --ar flag
