### ISSUE TITLE
Explicitly use IFS=' ' read on assume

### ISSUE THREAD

**Issue by bigluck** [common-fate/granted#349]
Hi everyone.
First thing first, this project is awesome; thanks very much.

I've tried for a while to integrate the `assume` command into my `direnv` workflow and... after some self-inflicted difficulties, I've found a slight improvement you can implement to make the script more resilient.

Long story short, my bash script has `IFS=$'\n'` at the beginning of the file, and this variable is interfering with the `read` command defined here: https://github.com/common-fate/granted/blob/fb360965a1589384c523a6b1bdcb254af8cd5d91/scripts/assume#L18

I've temporarily fixed it by invoking `IFS=' ' source assume my-profile`, but I think it worth to be settled directly on the assume script.

Thanks.

**Comment by chrnorm** [comment]
Great suggestion @bigluck - I will open a PR to fix this
