### ISSUE TITLE
Windows setup for granted registry fails if `.aws` does not exist

### ISSUE THREAD

**Issue by holly-evans** [common-fate/granted#355]
Hello, my colleagues use a Granted registry to set up AWS profiles on their Windows machines for the first time. The `granted registry add ...` command resulted in this error:

`[?] unable to create : open C:/Users/<username>/.aws/config: The system cannot find the path specified`

Once they created the `.aws` folder, it worked. I think ideally `granted registry add ...` would create that folder if missing, especially because it does create `config` if missing.

Additionally, they are all on Windows but I have not tried it on other systems without `.aws`.

Thanks!

**Comment by Eddie023** [comment]
@holly-evans Thank you for raising this issue. I think I have identified the issue, will try to replicate this issue and provide a fix!

**Comment by chrnorm** [comment]
Should be closed in #356!
