### ISSUE TITLE
AWS `generate`/`populate` commands should use `--sso-region` rather than `--region`

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#360]
Currently, Granted uses a `--region` flag to indicate the SSO instance region (`sso_region`) key in AWS config.
This flag should be used for the `region` key instead, and a new `--sso-region` flag should be introduced for the `sso_region` key. 

> One of the parameters is `region`, which will set the `sso_region` key in the config. 

> But I discovered today (I'm not a power user of AWS), that when I ran an `aws ecs` task that the `region` being used appears to be defaulting to the `sso_region`. 

> Because my tasks are running in a different region to the `sso_region`, my task was failing to find the ecs cluster I knew existed.

> I would suggest a comment mentioning that you will need to manually add the `region` key to your aws config generated by this command, if you don't add it manually to your cli commands. For me, because my accounts are segregated by region, it makes sense to add this into my config. For others, who use the region on the cli command it won't make sense. 

> I also think it would be a good idea to change the `--region` flag to be `--sso_region` to reflect how it will be used in the generated config. That's a breaking change of course, so that's more of hey it'd be good if in the future it changes. 

> Awesome project btw, very very handy.

_Originally posted by @benfreke in https://github.com/common-fate/granted/issues/271#issuecomment-1263035125_

**Comment by chrnorm** [comment]
Hi @benfreke, I certainly agree with your proposed change in #271 and I've opened this issue to track work on it.

I've introduced the `--sso-region` flag in #359, along with warnings indicating that we'll change the behaviour of `--region`.

We won't change the behaviour until a future version of Granted to give users time to migrate to the new flag. I'll leave this issue open until the breaking change has been made.

These are the warnings:

```
❯ granted sso generate https://example.awsapps.com/start
[!] Please specify the --sso-region flag: 'granted sso populate --sso-region us-east-1 https://example.awsapps.com/start'
[!] Currently, Granted defaults to using us-east-1 if this is not provided. In a future version, the --sso-region flag will be required to indicate the 'sso_region' field in generated profiles (https://github.com/common-fate/granted/issues/360)
```

```
dgranted sso generate --region ap-southeast-2 https://example.awsapps.com/start
[!] Please use --sso-region rather than --region.
[!] In a future version of Granted, the --region flag will be used to specify the 'region' field in generated profiles, rather than the 'sso_region' field. (https://github.com/common-fate/granted/issues/360)
```

To fix the warnings, use `--sso-region` rather than `--region`.

**Comment by n3s7or** [comment]
I think this issue can be closed. Almost a year already since the merge.
The option is not even there anymore.

```
$ granted -v && granted sso generate -h
Granted version: 0.31.0
NAME:
   granted sso generate - Prints an AWS configuration file to stdout with profiles from accounts and roles available in AWS SSO

USAGE:
   granted [global options] sso generate [command options] [sso-start-url]

OPTIONS:
   --config value                     Specify the SSO config section in the Granted config file ([SSO.name]) (default: "default")
   --prefix value                     Specify a prefix for all generated profile names
   --sso-region value                 Specify the SSO region
   --source value [ --source value ]  The sources to load AWS profiles from (valid values are: 'aws-sso', 'commonfate') (default: "aws-sso")
   --no-credential-process            Generate profiles without the Granted credential-process integration (default: false)
   --profile-template value           Specify profile name template (default: "{{ .AccountName }}/{{ .RoleName }}")
   --help, -h                         show help
```

**Comment by chrnorm** [comment]
Thankyou @n3s7or
