### ISSUE TITLE
Firefox Developer Edition does not open using assume -c

### ISSUE THREAD

**Issue by khill-wonde** [common-fate/granted#366]
It would appear that Firefox Developer Edition is supported to some degree, as the browser can be assigned using the steps described in this issue https://github.com/common-fate/granted/issues/99 

However, when running `assume -c` after setting FF DE as the browser of choice, the following error occurs.

[✘] Granted was unable to open a browser session automatically due to the following error: starting process: fork/exec /Applications/Firefox Developer Edition.app: permission denied

A unique URL is generated that can be copied and pasted into Firefox Developer Edition, but it would be great if the`assume -c` command could automatically open the browser to the correct URL like it does with the normal version of Firefox.

**Comment by meyerjrr** [comment]
Hi @khill-wonde, thanks for using Granted and submitting a issue!

I wasn't able to replicate this issue using FF DE, but the error you're receiving does indicate that you may not have execute permissions for the FF executable, as under the hood it is just running a simple bash command to open the console. 

A couple of things to try narrow down what might be causing this.
- What OS are you running?
- Have you tried any chmod commands to permit execution access to FF (`chmod +x path/to/file`)?
- Does this happen with any of the other browsers?

**Comment by shwethaumashanker** [comment]
Fix: https://github.com/common-fate/granted/pull/480
