### ISSUE TITLE
Improve MFA login experience by caching session tokens

### ISSUE THREAD

**Issue by smelchior** [common-fate/granted#371]
It would be great if granted could cache the session tokens after an MFA login that are used to assume roles in a non-SSO setup.
This would be for an aws cli config like:
```
[xy-base]
aws_access_key_id     = XXX
aws_secret_access_key = YYYY

[xy-operations]
role_arn       = arn:aws:iam::XXX:role/XY
mfa_serial     = arn:aws:iam::XXXX:mfa/XY
source_profile = xy-base
```

In this case i am currently prompted for my MFA each time i run the assume call and i am also limited to the role session limit time (which is mostly 1h)
I was using https://github.com/trek10inc/awsume/ before, and they implemented something to cache the credentials returned by the get-session-token call for the MFA authentication (https://github.com/trek10inc/awsume/blob/master/docs/general/overview.md?plain=1#L56) This makes life a lot easier when you have to assume the role in multiple shell sessions or want to also open it in the browser.

This was partially discussed in this https://commonfatecommunity.slack.com/archives/C0356DGLXME/p1677055552697469 +this https://commonfatecommunity.slack.com/archives/C0356DGLXME/p1675985537292519 (with a slightly different use-case) Slack thread

**Comment by orenmazor** [comment]
this would be really great! I jump between accounts all day and having to re-pull the MFA is kinda a bummer
