### ISSUE TITLE
Granted gives an error when used with Firefox Developer Edition

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#380]
> When running assume -c I’m now getting this message:
Granted was unable to open a browser session automatically due to the following error: starting process: fork/exec {homedir}/Applications/Firefox Developer Edition.app: permission denied
with a URL to open directly in my browser which does work
I’ve got Firefox Developer Edition set as my browser, done by pasting in the path to the executable for granted browser set. I’ve checked the permissions on the executable, and it is rwxr-xr-x so it should be executable by all (edited)

This may be due due to the fork/exec and open changes made in https://github.com/common-fate/granted/pull/375

**Comment by perpil** [comment]
Related: #366
