### ISSUE TITLE
IAM Federated logins should have attributable username.

### ISSUE THREAD

**Issue by matthewhembree** [common-fate/granted#387]
When using federated login with IAM credentials, the generated username is unique, but not easily attributable to a real user.

For instance, on the CloudTrail event entry for GetFederationTokenInfo, the user name might be `John Smith`, but the created federated user's user name would be something like `gntd-<random string>`.

This makes it hard to quickly attribute the real user to the federated user's events.

This is different from the assumed-role/SSO types of logins where the user name appears to correctly propagate into the session user (e.g. `John.Smith@company.com`).

Perhaps it's as simple as calling `GetCallerIdentity` and passing the response into the `Name` [parameter](https://github.com/common-fate/granted/blob/b9e8f2984869b7470b3da095ac639ba99e2ecbed/pkg/cfaws/assumer_aws_iam.go#L128) of `GetFederationToken`?.?.

Thanks!

**Comment by matthewhembree** [comment]
A additional side effect of the random name is that the AWS console preferences don't persist.

**Comment by shwethaumashanker** [comment]
Fixed in #469
