### ISSUE TITLE
`granted credentials rotate` does not delete the former credentials

### ISSUE THREAD

**Issue by matthewhembree** [common-fate/granted#388]
When running:

```
➜ granted credentials rotate
? Profile Name: default
[✔] Access Key of 'default' profile has been successfully rotated and updated in secure storage

➜ granted credentials rotate default
? Profile Name: default
[✘] operation error IAM: CreateAccessKey, https response error StatusCode: 409, RequestID: REDACTED, LimitExceeded: Cannot exceed quota for AccessKeysPerUser: 2
```

The former credentials are deactivated, but not deleted.

Thanks!

edit: wrong output. updated to be correct.

**Comment by n3s7or** [comment]
That feature was developed following AWS guidelines for [access key rotation](https://aws.amazon.com/blogs/security/how-to-rotate-access-keys-for-iam-users/), i.e. checking if your applications still working after updating to the new key, and if it doesn't you can rollback to the previous key. So if the previous access key was deleted there's no rolling back.

It's an easy change, just calling delete after [this line](https://github.com/common-fate/granted/blob/91242aa665a3614ffc9698ac8886b2ebaebd1f9b/pkg/granted/credentials.go#L577)

**Comment by montesuma** [comment]
It would be nice to have a configuration option for this. I think many people use aws key rotation on schedule via cron task
