### ISSUE TITLE
assume -c is not opening properly container in firefox 

### ISSUE THREAD

**Issue by eligro** [common-fate/granted#393]
Hey,

Thank you for your great tool! I've been using it for almost a year and it's saving me major time. 

I wanted to report an issue that started recently 

I'm simply running assume <role> -c , login works however when it tries to take me to the console, it's trying to search the following: 

```
ext+granted-containers:name=cynerio_developer&url=https%3A%2F%2Fsignin.aws.amazon.com%2Ffederation%3FAction%3Dlogin%26Destination%3Dhttps%253A%252F%252Fconsole.aws.amazon.com%252Fconsole%252Fhome%253Fregion%253Dus-east-1%26Issuer%3D%26SigninToken%3DTiOXwhKOBnYiZU3AAni55S5HtIiWquEJ74rM0Yx7glP-ysapNxgu4egcnxIqlyVQDJH0FEs70cldabwaxfJsQ ......
```

and it's not opening me a container like before. 

I'm not sure what changed. I have the latest Firefox (111.0.1 (64-bit))  and latest Assume version (0.9.1) 
I also have Firefox multi account containers installed and working fine when opening manually a container. 

Thanks.

<img width="993" alt="Screen Shot 2023-03-28 at 14 58 19" src="https://user-images.githubusercontent.com/1735903/228228920-c3a5e4c9-5a9e-4671-a082-2b677d4a7680.png">

**Comment by dsech** [comment]
It looks like you are missing the Granted Firefox extension https://addons.mozilla.org/en-GB/firefox/addon/granted/

Make sure it is installed and enabled.

**Comment by eligro** [comment]
Thank you, that was the issue
