### ISSUE TITLE
Add flag to open URL in browser using granted profile

### ISSUE THREAD

**Issue by sosheskaz** [common-fate/granted#398]
When running assume, it would be nice to be able to paste in a URL at the CLI to open that URL, instead of the console home page (or the service URL). For example, `assume my-profile --open https://console.aws.amazon.com/`

The reason I want this is so that I can send a colleague a link, and they can easily and quickly open it in the appropriate browser container in 1 step.

In that same vein it may be a nice feature to register a granted link (e.g. `granted:my-profile@https://console.aws.amazon.com/`) which could be sent to someone and run the appropriate `assume` command.

**Comment by perpil** [comment]
I believe this is available in .13 with the --cd/--console-destination flag.  https://docs.commonfate.io/granted/usage/console#opening-the-console-with-a-specific-destination Does that work for you?

**Comment by sosheskaz** [comment]
Yes
