### ISSUE TITLE
`assume` initial install should tolerate alternative alias configuration

### ISSUE THREAD

**Issue by jlm0x017** [common-fate/granted#415]
During my initial install, I ran straight into this:
```
$ assume
[i] To assume roles with Granted, we need to add an alias to your shell profile (https://docs.commonfate.io/granted/internals/shell-alias)
? Install bash alias at /Users/user/.bash_profile No
```
And it bombs.  Restarting the process returns to the same spot with no alternatives.

I curate my dotfiles, and I don't want your tool messing up my shell organization.  A link is already provided in the setup documenting what I need to do.  

**The install script should offer an option to add this alias manually.**

Better, would be if the script could detect that the alias is already set.  However, due to shell spawning, this can be problematic.  Just using `type` doesn't cut it.  If a shell genius could come along and implement this auto-detection, it would provide the best user experience.

In addition to offering an option in the install script to script this step, some additional documentation is needed.  I found (from https://github.com/common-fate/granted/issues/285) that setting `export GRANTED_ALIAS_CONFIGURED="true"` after the manual configuration allowed me to proceed past the failing step.  This detail should be included in the documentation (i.e. on page https://docs.commonfate.io/granted/internals/shell-alias).  Providing the documentation gives the user flexibility when installing the tool.  Skipping the question entirely, is a better user experience than just stopping the install to ask the user if this has already been done.

**Comment by shwethaumashanker** [comment]
Hi, @jlm0x017! Thanks for bringing up the issue! I have added the `export GRANTED_ALIAS_CONFIGURED="true"` to our docs.
