### ISSUE TITLE
Windows Installation Links 404

### ISSUE THREAD

**Issue by eigBabcock** [common-fate/granted#42]
All of the Windows installation links on the [getting started page](https://docs.commonfate.io/granted/getting-started) lead to "Page Not Found":

- https://docs.commonfate.io/granted/releases.commonfate.io/granted/v0.0.9/granted_0.0.9_windows_x86_64.zip
- https://docs.commonfate.io/granted/releases.commonfate.io/granted/v0.0.9/granted_0.0.9_windows_arm64.zip
- https://docs.commonfate.io/granted/releases.commonfate.io/granted/v0.0.9/granted_0.0.9_windows_i386.zip

**Comment by chrnorm** [comment]
Hey @eigBabcock, thanks very much for raising this issue (and congratulations for being the very first community contributor to the repo 😁). I've fixed the download links and updated the documentation to reflect this.

For your info the latest download links can be found here:

https://releases.commonfate.io/granted/v0.1.1/granted_0.1.1_windows_x86_64.zip
https://releases.commonfate.io/granted/v0.1.1/granted_0.1.1_windows_arm64.zip
https://releases.commonfate.io/granted/v0.1.1/granted_0.1.1_windows_i386.zip

Additionally there are some instructions [here](https://docs.commonfate.io/granted/security#release-verification) on how to verify the integrity and authenticity of the binaries.

If you have any further issues on Windows don't hesitate to raise an issue and we'll improve the project ASAP to deal with them. The core team maintaining the project predominantly uses unix-based machines, and while we did do enough Windows testing to feel comfortable stating that Windows is supported it is less battle-tested than Linux and MacOS.
