### ISSUE TITLE
Does not work in Cmd.exe session.

### ISSUE THREAD

**Issue by 296951** [common-fate/granted#448]
Granted is fantastic as long as you use it in Powershell or Git Bash.  It does not work in a `Cmd.exe` because it fails to set the `AWS_PROFILE` value correctly.  It seems to truncate the value.

See below:

![image](https://github.com/common-fate/granted/assets/76230985/f64fccc0-1470-4d85-bec0-f18fbd8f640d)

As you can see the profile selected does not match the profile set in `AWS_PROFILE` env variable.  The variable is missing the last 2 characters `AM`

The full profile name is 35 characters long.

**Comment by shwethaumashanker** [comment]
Hi @296951! Thank you for bringing up this issue. I've investigated the problem, and the issue has been resolved in pull request #465. This fix is included in our version [v0.14.4](https://github.com/common-fate/granted/releases/tag/v0.14.4)
