### ISSUE TITLE
Stop granted from automatically reassuming

### ISSUE THREAD

**Issue by samudurand** [common-fate/granted#453]
Is there any way to stop Granted to attempt to re-assume a session? Right now if I have used `assume` in a terminal, then next day I cannot use that terminal without granted forcing me to re-assume via the browser. I would prefer to have to do it manually since I do not need to always have an AWS session running.

**Comment by dannysteenman** [comment]
See the docs: https://docs.commonfate.io/granted/recipes/automatically_reassume on how to disable it.

**Comment by samudurand** [comment]
Thanks! I didn't see it because I was looking in the configuration
