### ISSUE TITLE
browser set-sso

### ISSUE THREAD

**Issue by wrighbr** [common-fate/granted#455]
Hi

I've noticed that when you use the command `granted browser set-sso -b chrome` it doesn't set the the config correctly in `~/.granted/config`

see below
```
 $ granted browser set-sso -b chrome
[✔] Granted will default to using  for SSO flows.
 $ cat .granted/config 
DefaultBrowser = "CHROME"
CustomBrowserPath = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
CustomSSOBrowserPath = ""
Ordering = ""
ExportCredentialSuffix = ""

[Keyring]
  Backend = "keychain"
```

Version: 0.14.0

**Comment by shwethaumashanker** [comment]
Hi @wrighbr, welcome to our community! You need to run `granted browser set-sso` which will give you the list of browsers you can choose from. We currently do not support adding the browser's name to the command. Hope this helps 😄 

<img width="891" alt="Screenshot 2023-09-01 at 3 08 41 PM" src="https://github.com/common-fate/granted/assets/32020525/8b6d819a-7d45-4eb5-9898-f61e81c7f6e8">
