### ISSUE TITLE
macOS:  invalid syntax in tap! 

### ISSUE THREAD

**Issue by nils2504** [common-fate/granted#46]
==> Tapping common-fate/granted
Cloning into '/opt/homebrew/Library/Taps/common-fate/homebrew-granted'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 88 (delta 22), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (88/88), 11.02 KiB | 2.20 MiB/s, done.
Resolving deltas: 100% (22/22), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/common-fate/homebrew-granted/Formula/granted.rb
formulae require at least a URL
Error: Cannot tap common-fate/granted: invalid syntax in tap!

Homebrew 3.3.16
MacBook Pro 14" 2021 - Apple M1 Pro with macOS Monterey (12.2.1)

**Comment by chrnorm** [comment]
Thanks for the issue @nils2504! I’ve realized that our Homebrew formula doesn’t handle ARM-based MacOS. I’ll update the formula now and reply to this issue once it’s fixed.

**Comment by chrnorm** [comment]
We've just released [v0.1.3](https://github.com/common-fate/granted/releases/tag/v0.1.3) which includes Apple Silicon binaries which should fix this issue!

You can update to this by re-running `brew install granted`. I've updated the [Granted Homebrew formula](https://github.com/common-fate/homebrew-granted/blob/main/Formula/granted.rb) to handle Apple Silicon. While I am this should work this is untested on ARM (I have an Intel device so can't test unfortunately). Please raise a new issue if you have any further issues installing Granted.

**Comment by nils2504** [comment]
Thanks a lot - amazing! I can commit it is working now! Nice Work!
