### ISSUE TITLE
How do I do string manipulations in `granted sso populate` ? Error `"strings" not defined`

### ISSUE THREAD

**Issue by nitrocode** [common-fate/granted#478]
## Context

I'd like to generate my profiles with the following template

```
{{ .RoleName }}-{{ .AccountName }}
```

I'd like to lowercase it using `strings.ToLower`. Here is an example from `gomplate` which works

```bash
$ echo '{ "RoleName": "Admin", "AccountName": "Prod" }' | gomplate -d test=stdin:///in.json -i '{{ (ds "test").RoleName | strings.ToLower }}-{{ (ds "test").AccountName | strings.ToLower }}'

admin-prod
```

Here is the error

```bash
$ granted sso populate --sso-region us-east-1 --prune --prefix gen_ --profile-template '{{ .RoleName | strings.ToLower }}-{{ .AccountName | strings.ToLower }}' https://<snip>.awsapps.com/start
[i] listing available profiles from AWS IAM Identity Center...
[✘] template: :1: function "strings" not defined
```

## Workaround

If I just want to lowercase, then it's pretty simple as I can lowercase all the profile names

```
granted sso generate --sso-region us-east-1 --profile-template '{{ .RoleName }}-{{ .AccountName }}' https://<snip>.awsapps.com/start | sed -e 's/\(\[profile.*\)/\L\1/'
```

But I'd also like to delete `-,.` n names and maybe do additional string manipulations. I suppose these can be done using sed as well.

## References

- https://github.com/common-fate/granted/blob/20cbb5c35b06a2bb22bf93895b144f6780cf5fa5/pkg/granted/sso.go#L19
- https://github.com/common-fate/granted/blob/20cbb5c35b06a2bb22bf93895b144f6780cf5fa5/pkg/granted/sso.go#L71-L76

Maybe the issue is in the common-fate/awsconfigfile package

- https://github.com/common-fate/awsconfigfile/blob/7c25334e72e65297e23e02cc6e413b81e208f44d/generator.go#L91-L93
- https://github.com/common-fate/awsconfigfile/blob/7c25334e72e65297e23e02cc6e413b81e208f44d/awscfg.go#L79-L84

Perhaps instead of using text/template, the masterminds/sprig library should be used instead?

**Comment by jmreicha** [comment]
Just tried this with v0.27.0 which should have the support but get an error. Here's the command I'm using ([adapted from release notes](https://github.com/common-fate/granted/releases/tag/v0.25.0)):

```
granted sso populate --sso-region us-west-2 --profile-template '{{ .RoleName | strings.ToLower }}/{{ .AccountName | strings.ToLower }}' https://d-92670a73b3.awsapps.com/start
```

Here's the error.

```
[✘] template: :1: function "strings" not defined
```

Am I just missing something simple?

**Comment by jmreicha** [comment]
Nevermind, this works. `--profile-template '{{ .RoleName | strings.ToLower }}/{{ .AccountName | strings.ToLower }}'`

**Comment by nitrocode** [comment]
Oh very nice. Thank you @mikesarver for the contribution and @jmreicha for confirming that it works.
