### ISSUE TITLE
Brave browser crashes after granted upgrade

### ISSUE THREAD

**Issue by houstonj1** [common-fate/granted#498]
I don't know which version this was introduced in, but previously I was able to create a new browser session using Brave with the following command 

```
assume -c
```

I noticed on version 0.16.1 that the same command now crashes all open instances of Brave. If anyone has any thoughts or solutions, much appreciated!

This is still the case after upgrading to the latest version 0.17.1, installed on an M1 Mac using Homebrew

Thanks in advance!

**Comment by Sunac** [comment]
I've noticed the same on Chrome after update to 0.17.1 on M1 Mac.

**Comment by Eddie023** [comment]
@houstonj1 Thanks for confirmation. 
Quick question: does your profile contain slashes? We have identified that profiles with slashes[ were failing for some users. ](https://github.com/common-fate/granted/issues/524) and we have recently pushed a fix for that https://github.com/common-fate/granted/pull/525 should be out in next release. Let me know if that fixes your issue!

**Comment by houstonj1** [comment]
This is now working in v0.19.2 🎉 Thanks for the work here @Eddie023
