### ISSUE TITLE
allow choosing chromium as the browser

### ISSUE THREAD

**Issue by trondhindenes** [common-fate/granted#53]
On linux, allow assume to use the Chromium browser if installed.

**Comment by chrnorm** [comment]
Thanks for the suggestion @trondhindenes. This should be very straightforward to add. We'll aim to include this in the next release.

**Comment by meyerjrr** [comment]
#73 Opened PR here supporting Chromium. @trondhindenes could I get you to confirm your path for chromium on linux? `/usr/bin/chromium`

**Comment by trondhindenes** [comment]
Oh, you need a path? That totally depends on how users have installed chromium. I would probably instead check if `chromium` is available on `PATH` and only show it if it is. That would allow you to cater for various installation methods

**Comment by meyerjrr** [comment]
Great idea, have added a check to PATH for the browser detection. Will fall back to manual input if it is not found.
