### ISSUE TITLE
Increase lifetime of the session credential

### ISSUE THREAD

**Issue by mlongarai** [common-fate/granted#58]
Hey guys,

First of all, thank you for creating this tool! ❤️

My question is very simple, would it be possible to increase the lifetime of the session credential? By parameter it would be awesome!

For those who use the terminal during all day, it is a bit annoying to have to renew it all the time.

`session credentials will expire 2022-02-25 08:21:14 +0000 WET`

Cheers!

**Comment by meyerjrr** [comment]
Hey @mlongarai! 

Thanks for the suggestion, this is something we could definitely get done for Granted. Will let you know when functionality is included.
