### ISSUE TITLE
Getting "invalid cross-device link" on registry sync (linux)

### ISSUE THREAD

**Issue by sirianni** [common-fate/granted#600]
On linux, `granted registry sync` fails:
```
$ granted registry sync
[i] From github.com:my_company/granted-registry
[i]  * branch            HEAD       -> FETCH_HEAD
[✔] Successfully synced registry my_company
[✘] rename /tmp/granted-registry-sync431384928/aws-config /home/sirianni/.aws/config: invalid cross-device link
```

Since `/tmp` is mounted from `tmpfs` the error message seems legitimate.

**Comment by sirianni** [comment]
@sosheskaz Seems related to https://github.com/common-fate/granted/pull/569 which uses `os.Rename()` to move the tmp config file onto `~/.aws/config`.

**Comment by christian-at-sevenlab** [comment]
Same issue here.
Downgrading to` 0.20.3` also fixes the issue

**Comment by sirianni** [comment]
If it's not possible to fix the issue can you advise how to locally build granted in a way that works with the standard config locations.  I'm having a very hard time with `dgranted`.

**Comment by sirianni** [comment]
This may have been fixed with the switch to `gopkg.in/ini.v1`

**Comment by chrnorm** [comment]
This should be fixed in #622, as we no longer write a temporary file. Is the issue still present in the latest release?

Sounds like we need to improve the docs on building from source too, thanks for flagging this @sirianni

**Comment by sirianni** [comment]
Yes it seems to work in the latest version.

**Comment by chrnorm** [comment]
Great - I’ve raised #656 to track the docs improvements.
