### ISSUE TITLE
For granted sso generate/populate commands add support to persist preferences in .granted/config

### ISSUE THREAD

**Issue by ibottamike** [common-fate/granted#650]
The granted sso generate/populate commands have input for StartURL, SsoRegion, Prefix, Source, NoCredentialProcess, and ProfileTemplate.

Only having the parameters available as input variables require them to be enter every time the commands are run. In a dynamic environment where AWS accounts are added/removed, this requires the variables to be stored outside of granted configuration.  

Add the capability to store the configuration values in `.granted/config` to be consistent with `registry add/sync` and assume browser preferences.

**Comment by chrnorm** [comment]
Implemented in #651!
