### ISSUE TITLE
granted sso generate is not returning all accounts

### ISSUE THREAD

**Issue by moltar** [common-fate/granted#669]
Running:

```
granted sso generate --sso-region=us-east-1 https://foo.awsapps.com/start
```

Produces a config with most of the accounts, but one there.

When visiting `https://foo.awsapps.com/start` page, the account _is_ there.

I have tried clearing all cache.

Any suggestions?

**Comment by moltar** [comment]
Closing, as this morning, it self-resolved.

No idea why. I did not change anything since yesterday.

It could not have been a cache session because I have cleared them all using granted CLI.

**Comment by chrnorm** [comment]
Good to hear it’s resolved @moltar. I am wondering if the account was recently assigned via a group membership? We’ve had reports that you need to log out and in in order for the group membership accounts to refresh.

**Comment by moltar** [comment]
I granted direct access to the account to my user.

Also, the account _was_ visible in both UI and API (via AWS CLI) to my user.

It was only not picked up via granted.
