### ISSUE TITLE
Sort generated/populated profiles alphabetically?

### ISSUE THREAD

**Issue by jmreicha** [common-fate/granted#674]
I have a decent number of profiles to manage and it looks like the generate/populate commands don’t have an option to sort the profile names alphabetically.

It would make the management of large numbers of profiles easier if this was either the default behavior or an option that could be specified.

**Comment by jmreicha** [comment]
Could someone point me where to start looking? I can look at adding this if it is straight forward.

**Comment by n3s7or** [comment]
In the meantime, one thing to consider is that you can actually filter your profiles:

$ assume

? Please select the profile you would like to assume:  [Use arrows to move, **type to filter**]
