### ISSUE TITLE
Config Filed does not exist

### ISSUE THREAD

**Issue by jrwpatterson** [common-fate/granted#688]
Hi I am trying to use your wonderful software and I've used it tonnes in the past. 

But a weird thing is happening. Its logging in, but when it comes back, I'm getting an error of 

```
[✘] config file does not exist
```

No information why thats happening I've searched your repo and I can't find that anywhere in the code base! Its killing me!

The same config works on other users machines. I've deleted, reinstalled, nuked the cache, nuked the session token 

To make matters weirder it works with some configs that are identical bar the roll name or account number

**Comment by meyerjrr** [comment]
Hi @jrwpatterson! Would you be able to run what is causing your issues with the GRANTED_LOG env variable set to debug? This will help in diagnosing where the config file read is getting called.

eg.
```
export GRANTED_LOG=debug && assume 
```

**Comment by jrwpatterson** [comment]
Ok I'll have a look Monday seems to happen sometimes and sometimes it's fine!

**Comment by douglaspetrin** [comment]
this is probably happening because you're missing the .aws/credentials file, or perhaps in your config file you are trying to download it but somehow it is not able to. for i.e: under your profile in your .aws/config file you have something like this to download your credentials:

[profile my_profile]
credential_process = granted credential-process --auto-login --profile my_profile

see: https://docs.commonfate.io/granted/recipes/credential-process

**Comment by jrwpatterson** [comment]
sorry stuck again 

```[i] To assume this profile again later without needing to select it, run this command:
> assume Lasoo-AdministratorAccess-prod --env
2024/07/18 15:15:32 [keyring] Considering backends: [keychain]
2024/07/18 15:15:32 [keyring] Querying keychain for service="granted-aws-sso-tokens", account="https://d-.awsapps.com/start/base", keychain="login.keychain"
2024/07/18 15:15:32 [keyring] No results found
[DEBUG] error retrieving IAM Identity Center token from secure storage: The specified item could not be found in the keyring
2024/07/18 15:15:32 [keyring] Considering backends: [keychain]
2024/07/18 15:15:32 [keyring] Checking keychain status
2024/07/18 15:15:32 [keyring] Keychain status returned nil, keychain exists
2024/07/18 15:15:32 [keyring] Keychain item trusts keyring
2024/07/18 15:15:32 [keyring] Adding service="granted-aws-sso-tokens", label="", account="https://d-.awsapps.com/start/base", trusted=true to osx keychain "login.keychain"
2024/07/18 15:15:32 [keyring] Considering backends: [keychain]
2024/07/18 15:15:32 [keyring] Removing keychain item service="granted-aws-sso-tokens", account="https://d-976706ccc7.awsapps.com/start/", keychain "login.keychain"
[DEBUG] clearing sso token from the credentials cache: The specified item could not be found in the keyring
[✘] operation error SSO: GetRoleCredentials, https response error StatusCode: 401, RequestID: 2db0d626-ca69-4e1a-a5e4-28cb820828d2, UnauthorizedException: Session token not found or invalid```
