### ISSUE TITLE
Problems with Assuming roles with MFA 

### ISSUE THREAD

**Issue by daknhh** [common-fate/granted#69]
Hello, when i try to assume a role with mfa the following Error occur:
` assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.`

I think its because the SDK doesn’t automatically set the AssumeRoleTokenProvider with a default value. This is because of the risk of halting an application unexpectedly while the token provider waits for a nonexistent user to provide a value due to a configuration change. You must set this value to use MFA roles with the SDK.

**Comment by meyerjrr** [comment]
Hey @daknhh! Thanks for highlighting this issue.
Granted currently doesn't support MFA but it is definitely something that we want to be included soon. Would be a simple requirement to achieve as you noted.
We have ticketed this internally and will inform you when we get it into a release.
