### ISSUE TITLE
Map between AWS profiles and browser profiles

### ISSUE THREAD

**Issue by kaihendry** [common-fate/granted#782]
I'm a bit bewildered by your docs https://docs.commonfate.io/granted/configuration/#using-specific-browser-profiles and SSOBrowserLaunchTemplate config

Be good to please have bash completion!

```
❯ granted completion -s bash
[i] We don't have completion support for bash yet, check out our docs to find out how to let us know you want this feature https://granted.dev/autocompletion
```

I wrote a blog about how I'm using granted currently: https://dabase.com/blog/2024/aws-sso/

My expectation is that the config is something more sane like:

```
[ProfileMapping]
  "Admin-123" = "Profile 4"
  "Admin-321" = "Profile 12"
```

Please tell me there is a simpler way. Thank you!

**Comment by chrnorm** [comment]
Thankyou for sharing the blog post @kaihendry! And fair point on the docs for this, it seems like we can make this clearer.

Profile mapping isn't supported but we'd like to add it, would the solution proposed in #771 work for you?

**Comment by kaihendry** [comment]
Oh yeah, https://github.com/common-fate/granted/issues/771 looks good!
