### ISSUE TITLE
We don't recognize service bedrock but we'll try and open it anyway

### ISSUE THREAD

**Issue by felipewnp** [common-fate/granted#783]
Hi.

When launching bedrock from `assume` command returns this error:

```
assume -c my-profile -s bedrock
[!] We don't recognize service bedrock but we'll try and open it anyway (you may receive a 404 page)
```

I thought it was an outdated version, but `granted -v` shows `0.35.1`, the current latest.

And yes, It opens was bedrock page correctly.

So I think "bedrock" just needed to be added somewhere in the code. Maybe  [pkg/console/service_map.go](https://github.com/common-fate/granted/blob/main/pkg/console/service_map.go) ?

I can open a PR if it's the right file.

**Comment by chrnorm** [comment]
That file is indeed the right one - a PR here would be most welcomed!

**Comment by felipewnp** [comment]
Done! @chrnorm 

#784

**Comment by chrnorm** [comment]
Completed in #784
