### ISSUE TITLE
Handle global services automatically

### ISSUE THREAD

**Issue by sidick** [common-fate/granted#87]
For some services like Route53, if you specify that to open the console to, it tries to go to the regional version, and that one especially is global. Others I'm aware of are chime, iam and s3, though there are likely more.

**Comment by chrnorm** [comment]
Thanks for the issue @sidick - our mapping [here](https://github.com/common-fate/granted/blob/4f9262d6e0baaca79145a96ddcd568b45482f112/pkg/browsers/console.go#L279) is incomplete and definitely needs work (currently it just handles the `iam` service).

I'm not sure if a definitive list of global services exists in AWS's documentation so a fix here might need to run through the current services in the console and note the ones which are global. Thanks for noting a few examples (Route53, Chime, IAM, S3), I think CloudFront is also global.

We should probably specify whether a service is global or regional in the [ServiceMap](https://github.com/common-fate/granted/blob/4f9262d6e0baaca79145a96ddcd568b45482f112/pkg/browsers/console.go#L23-L50) definitions.
