### ISSUE TITLE
Feature Request: Documentation Auto-Update

### ISSUE THREAD

**Issue by QuinnyPig** [common-fate/granted#88]
The "[how to install this](https://docs.commonfate.io/granted/getting-started)" portion of the documentation site has v0.1.3 hardcoded; the GitHub workflow build action should ideally kick that version string up a notch on every release so you're not having new users install an old version.

**Comment by meyerjrr** [comment]
Thanks for the heads up on this one @QuinnyPig. This has been flagged internally and are aiming to get this fixed ASAP.

**Comment by meyerjrr** [comment]
Update on this. We have pushed out a fix in our builds repo for Github actions to update version numbers on new builds going live.

Not currently open sources but we are looking to make the docs repo public soon. 

Thanks for the heads up on this @QuinnyPig.
