### ISSUE TITLE
Allow stdout as a browser option

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#90]
Raised by @QuinnyPig in #78 - splitting this so we can track this issue separately.

In display-constrained devices (such as a remote SSH connection to a server, where the server is running the Granted binary) Granted users don’t have access to the browser on the same device which is executing Granted.

In this situation, it’s desirable to print the resulting console URL to STDOUT so that users can copy this out of the SSH session and into their host system, which is likely to have a web browser.

The desired experience for this is something like:
```bash
granted browser set —browser=stdout
assume -c PROFILE_NAME
# a console URL for PROFILE_NAME is printed in the terminal
```

**Comment by meyerjrr** [comment]
Partially added this functionality in #78 @chrnorm. `assume PROFILE_NAME -u` will print the url to STDOUT for the user to be able to manually copy from there or alternatively use `open $(assume PROFILE_NAME -u) 

We can keep this open if we alternatively want to create a browser type of *no_browser*

**Comment by JoshuaWilkes** [comment]
A benefit to the -url flag that @meyerjrr  referenced is you can set your browser to firefox and the url returned will be a firefox url with the extension config. Alternatively, setting your browser to Chrome with return a url the you can launch in any browser.

**Comment by QuinnyPig** [comment]
Then "Chrome / None" should be the menu option since it's arguably undiscoverable otherwise?

**Comment by meyerjrr** [comment]
Hey @QuinnyPig thanks for the suggestion!, We have gone with a more silent/background method to add this functionality in #82. Whereby Granted won't explicitly have a *no browser* option, but will silently fallback to return a link if browser functionality fails. In this case we don't need to worry about the discoverability of the option. 
If the user wanted to manually return the URL then they have the -u option in the cli
