### ISSUE TITLE
Granted gives “incorrect function” on Windows git bash

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#94]
Raised by David in the Common Fate Community Slack:

The “assume” command fails on Windows git bash with the error “incorrect function”.

**Comment by waltzbucks** [comment]
I've ran into else problem at similar  environment with this capture.
```
exec: "": executable file not found in %PATH%
```
![image](https://user-images.githubusercontent.com/47586500/157603527-3107178a-3d08-4781-9c27-2713704da7fe.png)

in this environment by git bash on Windows 11. Also I've already setup system environment variables by granted Path.
