### ISSUE TITLE
Firefox Dev Edition

### ISSUE THREAD

**Issue by DWSR** [common-fate/granted#99]
Hey all, are there specific instructions for using Granted with FF Dev Edition?

**Comment by meyerjrr** [comment]
Hey @DWSR, there are no specific instructions for the Dev Edition of Firefox. Were you able to set your default browser in the Granted setup? 

Currently if Granted does not allow for adding custom browsers, as in passing through a path to their browser of choice. 

Do you have normal Firefox installed and able to set up Granted with that version of Firefox?

**Comment by JoshuaWilkes** [comment]
@DWSR 

Updating this ticket, we introduced a flag for the path as a shortcut to custom configure a browser.

For your use-case you should be able to run `granted browser set -b firefox -p /path/to/my/browser`
This will setup your Firefox dev browser.

Let us know how this goes
